spring.application.name=associacao-gaia-api

# CONFIGURACAO DO BANCO DE DADOS - ASSOCIACAO GAIA
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/associacao_gaia?useSSL=false&serverTimezone=America/Sao_Paulo&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:SUASENHABD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Garante que o Spring use a porta injetada pelo Render
server.port=${PORT:8080}

# JWT chave usada para assinar/validar os tokens
api.security.token.secret=${JWT_SECRET:chave-super-secreta-do-projeto-gaia-trocar-depois-2026}
api.security.token.expiracao-minutos=120
